config/routes.rb
Rails.application.routes.draw do

devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }
get 'photos' => 'photos#index'
root to: 'photos#index'

resources :photos do
  member do
    post 'like'
  end
  resources :comments
end

devise_scope :user do
  resources :users
end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :photo
  belongs_to :user
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :photo
  belongs_to :user

validates_uniqueness_of :user, scope: :photo
  
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_attached_file :image, :styles => { :medium => "300X300>", :thumb => "100x100>" }, :default_url => '/images/:style/missing.png'
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  validates :name, length: { minimum: 3 }, presence: :true
  validates :description, length: { minimum: 10 }, presence: :true
  validates :image, presence: true
  validates :user_id, presence: true
  default_scope -> { order(updated_at: :desc) }

  def thumbs_up_total
    self.likes.where(like: true).size
  end

  def thumbs_down_total
    self.likes.where(like: false).size
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :omniauthable, :omniauth_providers => [:facebook]

  has_many :photos, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  

def self.from_omniauth(auth)
  where(provider: auth["provider"], uid: auth["uid"]).first_or_create do |user|
    user.email = auth["info"]["email"] unless auth["info"]["email"].blank?
    user.password = Devise.friendly_token[0,20]
    # user.name = auth.info.name   # assuming the user model has a name
    # user.image = auth.info.image # assuming the user model has an image
   end
 end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!, :except => [:index, :show]
  
  def comment_params
    params.require(:comment).permit(:thoughts)
  end

  def new
    @photo = Photo.find(params[:photo_id])
    @comment = Comment.new
  end

  def create
    @photo = Photo.find(params[:photo_id])
    @comment = @photo.comments.build(comment_params.merge(user: current_user))
    @comment.save
    redirect_to photo_path(@photo)
  end

  def posted_at
    (Time.now - comment.created_at).ago_in_words
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @photo = Photo.find(params[:photo_id])
    @like = @photo.likes.build(user: current_user)
    @like.save
    # render json: {new_like_count: @photo.likes.count}
    flash[:success] = "Your selection was successful"
    redirect_to :back 
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  
  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @photos = Photo.paginate(page: params[:page], per_page: 3)
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params.merge(user: current_user))
    # add @photo.user == current_user
      if @photo.save
        flash[:success] = "Posted!"
        redirect_to photos_path
      else
        render :new
      end
  end

  def like
    @photo = Photo.find(params[:id])
    like = Like.create(like: params[:like], user: User.first, photo: @photo) #change user to current_user
    if like.valid?
      flash[:success] = "Your selection was successful!"
    else 
      flash[:danger] = "You can only like/dislike a photo once."
    end
      redirect_to :back
  end

  private

    def photo_params
      params.require(:photo).permit(:image, :name, :description)
    end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

   def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.paginate(page: params[:page], per_page: 3)
  end

  def show
    @user = User.find(params[:id])
    @photos = @user.photos.paginate(page: params[:page], per_page: 3)
  end

end 

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = { size: 20 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.email, class: "gravatar")
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/comments/new.html.erb
<%= form_for [@photo, @comment] do |f| %>
  <%= f.label :thoughts %>
  <%= f.text_area :thoughts %>
  <%= f.submit 'Leave Comment' %>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="center"><h3><%= link_to 'All Photos', photos_path, class: "btn btn-warning btn-small" %></h3></div>
  <p>&copy; ITUgram 2015</p>
</div>

app/views/layouts/_message.html.erb
<div class="row">
  <div class="col-md-10">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %>
        <a class="close" data-dismiss="alert">&#215;</a>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <%= link_to "ITUgram", photos_path, class: "btn btn-lg btn-success", id: "logo" %>
    <%= link_to "Users", users_path, class: "btn btn-lg btn-default", id: "users" %>
    <% if user_signed_in? %>
      <div class="nav-item">
        <%= link_to 'Profile', user_path(current_user), class: "btn btn-lg btn-default", id: "user-profile" %>
        <%= link_to 'Add a photo', new_photo_path, class: "btn btn-lg btn-success", id: "add-photo" %>
        <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "btn btn-default btn-warning", id: "signout" %>
    </div>
      <% else %>
        <div class="nav-item">
          <%= link_to 'Sign in', new_user_session_path, class: "btn btn-default btn-warning" %>
        </div>
        <div class="nav-item">
          <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-default btn-warning" %>
        </div>
        <div class="nav-item">
          <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook), class: "btn btn-default btn-primary" %>
        </div>
      <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
<meta charset="UTF-8">
  <title>ITUgram</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

  <%= render 'layouts/navigation' %>

  <div class="container">
    <%= render 'layouts/message' %>
    <%= yield %>
    
  <%= render 'layouts/footer' %>

  </div>

</body>
</html>

app/views/photos/_form.html.erb
<%= render 'shared/errors', obj: @photo %>

<div class="row">
  <div class="well col-md-8 col-md-offset-2">
    <%= form_for @photo, html: {multipart: true}  do |f| %>
      <%= f.label :image, "Image" %>
      <%= f.file_field :image %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :description %>
      <%= f.text_area :description, rows: 3 %>

      <%= f.submit 'Submit Photo', class: "btn btn-success"%>
    <% end %>
  </div>
</div>

app/views/photos/index.html.erb
<%= render 'shared/page_title', title: "Latest Photos" %>

<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%= will_paginate %>
  </div>
</div>

<div class="center">
  <% if @photos.any? %>
    <div class="column">
    <% @photos.each do |photo| %>
      <div class="well col-md-8 col-md-offset-2">
        <h1><%= link_to photo.name, photo_path(photo) %></h1> 
        <%= link_to gravatar_for(photo.user, size: 50), user_path(photo.user) %>
        <h4><%= "Posted by #{photo.user.email}" %></h4>
        <span class="quiet"><small> <%= time_ago_in_words(photo.created_at) %> ago</small></span>
        <h3 class='image'> <%= link_to photo_path(photo) do %>
        <%= image_tag photo.image.url(:original), {:width => "400", :height => "400"} %></h3> 
        <% end %>
        <p><%= photo.description %></p> 
        <%= link_to like_photo_path(photo, like: true), method: :post do %>
        <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= photo.thumbs_up_total %>
        <% end %> &nbsp&nbsp&nbsp&nbsp
        <%= link_to like_photo_path(photo, like: false), method: :post do %>
        <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp <%= photo.thumbs_down_total %>
        <% end %>  
        <br>
        <%= link_to "Comment", new_photo_comment_path(photo) %></br>
        <% if photo.comments.any? %>
            <% photo.comments.each do |comment| %>
                <h6><%= comment.thoughts %> - <%= "Posted by #{comment.user_id}" %></h6>
            <% end %>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <h1>No photos yet!</h1>
  <% end %>
</div>

<%= will_paginate %>

app/views/photos/new.html.erb
<%= render 'shared/page_title', title: "Share a Photo" %>


<%= render 'form' %>

app/views/photos/show.html.erb
<%= render 'shared/page_title', title: @photo.name %>

<div class="center">
  <%= link_to gravatar_for(@photo.user, size: 80), user_path(@photo.user) %>
  <h4><%= "Posted by #{@photo.user.email}" %></h4>
  <h3 class='image'><%= image_tag @photo.image.url(:original), {:width => "500", :height => "500"}%></h3>
  <p><%=@photo.description %></p>
    <%= link_to like_photo_path(@photo, like: true), method: :post do %>
      <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= @photo.thumbs_up_total %>
    <% end %> &nbsp&nbsp&nbsp&nbsp
    <%= link_to like_photo_path(@photo, like: false), method: :post do %>
      <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp <%= @photo.thumbs_down_total %>
    <% end %>
    <br>
  <%= link_to "Comment", new_photo_comment_path(@photo) %></br>
  <% if @photo.comments.any? %>
      <% @photo.comments.each do |comment| %>
         <h6><%= comment.thoughts %> - <%= "Posted by #{comment.user_id}" %></h6>
      <% end %>
  <% else %>
    <p>Be the first to comment on this photo</p>
  <% end %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="alert alert-danger col-md-8 col-md-offset-2">
      <h5>Please correct the following errors</h5
      <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_page_title.html.erb
<p>
  <h1><%= title %></h1>
  <hr/>
</p>

app/views/users/index.html.erb
<%= render 'shared/page_title', title: "ITUgramians" %>

<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%= will_paginate %>
  </div>
</div>

<% @users.each do |user| %>
  <div class="row">
    <div class="col-md-4 col-md-offset-4 center">
      <%= link_to gravatar_for(user, size: 200), user_path(user) %>
      <p>
        <h5>User: <%= user.email %> </h5>
      </p>
    </div>
  </div>
<% end %>
<div class="center">
  <%= will_paginate %>
</div>

app/views/users/show.html.erb
<%= render 'shared/page_title', title: @user.email %>

<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%= link_to gravatar_for(@user, size: 100), user_path(@user) %>
    <hr/>
    <%= will_paginate @photos %>
  </div>
</div>

<div class="center">
  <% if @photos.any? %>
    <div class="column">
    <% @photos.each do |photo| %>
      <div class="well col-md-8 col-md-offset-2">
        <h1><%= link_to photo.name, photo_path(photo) %></h1> 
        <%= link_to gravatar_for(photo.user, size: 50), user_path(photo.user) %>
        <h4><%= "Posted by #{photo.user.email}" %></h4>
        <span class="quiet"><small> <%= time_ago_in_words(photo.created_at) %> ago</small></span>
        <h3 class='image'> <%= link_to photo_path(photo) do %>
        <%= image_tag photo.image.url(:original), {:width => "400", :height => "400"} %></h3> 
        <% end %>
        <p><%= photo.description %></p> 
        <%= link_to like_photo_path(photo, like: true), method: :post do %>
        <i class="glyphicon glyphicon-thumbs-up"></i> &nbsp <%= photo.thumbs_up_total %>
        <% end %> &nbsp&nbsp&nbsp&nbsp
        <%= link_to like_photo_path(photo, like: false), method: :post do %>
        <i class="glyphicon glyphicon-thumbs-down"></i> &nbsp <%= photo.thumbs_down_total %>
        <% end %>  
        <br>
        <%= link_to "Comment", new_photo_comment_path(photo) %></br>
        <% if photo.comments.any? %>
            <% photo.comments.each do |comment| %>
                <h6><%= comment.thoughts %> - <%= "Posted by #{comment.user_id}" %></h6>
            <% end %>
        <% end %>
      </div>
      <hr/>
    <% end %>
  <% else %>
    <h1>No photos yet!</h1>
  <% end %>
</div>

<%= will_paginate @photos %>